services:
  - type: web
    name: quiz-system
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: quiz-db
    databaseName: quiz_system
    user: quiz_user
    plan: free